// Estructura de batería para el ejercicio de clasificación (Drag & Drop)
// Categorías: 0: Frutas, 1: Animales, 2: Ropa, 3: Herramientas

window.bateria1 = {
    categorias: ["Afirmación", "Cantidad", "Duda", "Lugar", "Modo", "Negación", "Tiempo"],
    palabras: [

        { texto: "Aquí", cat: 3 },
        { texto: "Allí", cat: 3 },
        { texto: "Ahí", cat: 3 },
        { texto: "Allá", cat: 3 },
        { texto: "Cerca", cat: 3 },
        { texto: "Lejos", cat: 3 },
        { texto: "Arriba", cat: 3 },
        { texto: "Abajo", cat: 3 },
        { texto: "Fuera", cat: 3 },
        { texto: "Dentro", cat: 3 },
        { texto: "Alrededor", cat: 3 },
        { texto: "Encima", cat: 3 },
        { texto: "Debajo", cat: 3 },
        { texto: "Detrás", cat: 3 },
        { texto: "Delante", cat: 3 },
        { texto: "Hoy", cat: 6 },
        { texto: "Ayer", cat: 6 },
        { texto: "Mañana", cat: 6 },
        { texto: "Ahora", cat: 6 },
        { texto: "Luego", cat: 6 },
        { texto: "Después", cat: 6 },
        { texto: "Antes", cat: 6 },
        { texto: "Pronto", cat: 6 },
        { texto: "Tarde", cat: 6 },
        { texto: "Siempre", cat: 6 },
        { texto: "Nunca", cat: 6 },
        { texto: "Jamás", cat: 6 },
        { texto: "Todavía", cat: 6 },
        { texto: "Ya", cat: 6 },
        { texto: "Mientras", cat: 6 },
        { texto: "Bien", cat: 4 },
        { texto: "Mal", cat: 4 },
        { texto: "Así", cat: 4 },
        { texto: "Deprisa", cat: 4 },
        { texto: "Despacio", cat: 4 },
        { texto: "Mejor", cat: 4 },
        { texto: "Peor", cat: 4 },
        { texto: "Peor", cat: 4 },
        { texto: "Igual", cat: 4 },
        { texto: "Gratuitamente", cat: 4 },
        { texto: "Claramente", cat: 4 },
        { texto: "Mucho", cat: 1 },
        { texto: "Poco", cat: 1 },
        { texto: "Muy", cat: 1 },
        { texto: "Casi", cat: 1 },
        { texto: "Más", cat: 1 },
        { texto: "Menos", cat: 1 },
        { texto: "Bastante", cat: 1 },
        { texto: "Demasiado", cat: 1 },
        { texto: "Nada", cat: 1 },
        { texto: "Sí", cat: 0 },
        { texto: "También", cat: 0 },
        { texto: "Efectivamente", cat: 0 },
        { texto: "No", cat: 5 },
        { texto: "Tampoco", cat: 5 },
        { texto: "Jamás", cat: 5 },
        { texto: "Quizás", cat: 2 },
        { texto: "Acaso", cat: 2 },
        { texto: "Posiblemente", cat: 2 },
        { texto: "Probablemente", cat: 2 },




    ]
};
